@Library('testInParallel') _
testInParallel(count(5), 'inclusions.txt', 'exclusions.txt', 'target/surefire-reports/TEST-*.xml', 'maven:3.3.9-jdk-8', {
  checkout scm
}, {
  wrap([$class: 'ConfigFileBuildWrapper', managedFiles: [[fileId: 'jenkins-mirror', variable: 'SETTINGS']]]) {
    sh 'mvn -s $SETTINGS -B clean test -Dmaven.test.failure.ignore'
  }
})
