@Library('testInParallel') _

properties([
    parameters([
        string(name: 'MULTIPLIER', defaultValue: '1', description: 'Factor by which to artificially slow down tests.'),
        string(name: 'SPLIT', defaultValue: '5', description: 'Number of buckets to split tests into.')
    ])
])

stage('Sources') {
  node {
    checkout scm
    stash name: 'sources', excludes: 'Jenkinsfile,hello/target/,goodbye/target/'
  }
}

stage('Testing Hello') {
  testInParallel(count(Integer.parseInt(params.SPLIT)), 'hello/inclusions.txt', 'hello/exclusions.txt',
      'target/surefire-reports/TEST-*.xml', 'maven:3.5.0-jdk-8', "Testing Hello", {
    unstash 'sources'
  }, {
    configFileProvider([configFile(fileId: 'jenkins-mirror', variable: 'SETTINGS')]) {
      withEnv(["MULTIPLIER=$params.MULTIPLIER"]) {
        sh 'cd hello && mvn -s $SETTINGS -B clean test -Dmaven.test.failure.ignore'
        junit "hello/target/surefire-reports/*.xml"
      }
    }
  })
}

stage('Testing Goodbye') {
  testInParallel(count(Integer.parseInt(params.SPLIT)), 'goodbye/inclusions.txt', 'goodbye/exclusions.txt',
      'target/surefire-reports/TEST-*.xml', 'maven:3.5.0-jdk-8', "Testing Goodbye", {
    unstash 'sources'
  }, {
    dir('goodbye') {
      configFileProvider([configFile(fileId: 'jenkins-mirror', variable: 'SETTINGS')]) {
        withEnv(["MULTIPLIER=$params.MULTIPLIER"]) {
          sh 'cd goodbye && mvn -s $SETTINGS -B clean test -Dmaven.test.failure.ignore'
          junit "goodbye/target/surefire-reports/*.xml"
        }
      }
    }
  })
}
