@Library('testInParallel') _

properties([
  parameters([
    string(name: 'MULTIPLIER', defaultValue: '1', description: 'Factor by which to artificially slow down tests.'),
    string(name: 'SPLIT', defaultValue: '5', description: 'Number of buckets to split tests into.')
  ])
])

stage('Sources') {
  node {
    checkout scm
    dir('hello') {
      stash name: 'hello', excludes: 'target/'
    }
    dir('goodbye') {
      stash name: 'goodbye', excludes: 'target/'
    }
  }
}

stage('Testing Hello') {
  testInParallel(count(Integer.parseInt(params.SPLIT)), javaTestCase(), 'inclusions.txt', 'exclusions.txt', 'Testing Hello', {
    unstash 'hello'
  }, {
    configFileProvider([configFile(fileId: 'jenkins-mirror', variable: 'SETTINGS')]) {
      withEnv(["MULTIPLIER=$params.MULTIPLIER"]) {
        sh 'mvn -s $SETTINGS -B -ntp -Dmaven.test.failure.ignore clean test'
        junit 'target/surefire-reports/*.xml'
      }
    }
  })
}

stage('Testing Goodbye') {
  testInParallel(count(Integer.parseInt(params.SPLIT)), javaTestCase(), 'inclusions.txt', 'exclusions.txt', 'Testing Goodbye', {
    unstash 'goodbye'
  }, {
    configFileProvider([configFile(fileId: 'jenkins-mirror', variable: 'SETTINGS')]) {
      withEnv(["MULTIPLIER=$params.MULTIPLIER"]) {
        sh 'mvn -s $SETTINGS -B -ntp -Dmaven.test.failure.ignore clean test'
        junit 'target/surefire-reports/*.xml'
      }
    }
  })
}
